# Site settings
title: "OBORCHAIN - Blockchain solutions for One Belt & One Road Project Member Countries"
email: "info@oborchain.org"
description: "Blockchain solutions for One Belt & One Road Project Member Countries"
keywords: "oborchain, ico, funding, ethereum, eth"
url: "https://oborchain.github.io" # the base hostname & protocol for your site
twitter_username: aruzikulov
github_username:  oborchain
sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown

exclude:
  - .git/
  - .github/
  - assets/scss/
  - build/
  - js/
  - node_modules/
  - scss/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - package.js
  - package.json
  - package-lock.json
  - README.md

baseurl: "" # the subpath of your site, e.g. /blog/
pagesurl: "/pages"
vendorsurl: "/assets/vendors"
imgurl: "/assets/img"
imageurl: "/assets/img"
cssurl: "/assets/css"
jsurl: "/assets/js"
